---
title: "R Notebook"
output: github_document
---

 

```{r}
library(tidyverse)
```

```{r}
percentile_80 <- function(x){return(quantile(x, 0.8))[[1]]}
percentile_20 <- function(x){return(quantile(x, 0.2))[[1]]}
```


```{r}
answers_to_plot <- read_csv("Mohanad_prelim_answers.csv")
```

```{r}
answers_to_plot <- answers_to_plot %>% 
  gather(key = answer_num, value = answer_result, 1:21) %>% 
  mutate(answer_num = stringr::str_sub(answer_num, 8, -1)) %>% 
  mutate(answer_num = as.integer(answer_num))
  
```

```{r}
ggplot(answers_to_plot) + 
  stat_summary(mapping = aes(answer_num, answer_result), fun.ymin = "min", fun.y = "mean", fun.ymax = "max", size = 0.2) + 
  scale_y_continuous("Estimate", limits = c(0, 1)) + scale_x_continuous("Question", breaks = seq(1, 21), labels = seq(1, 21)) + theme_bw()
```

```{r}
ggsave("Answers_plot.pdf", width = 10, height = 3)
```




```{r}
ggplot(answers_to_plot) + 
  stat_summary(mapping = aes(x = answer_num, y = answer_result), fun.ymin = percentile_20, fun.y = "mean", fun.ymax = percentile_80, size = 0.2, colour = "blue") + 
  scale_y_continuous("Estimate", limits = c(0, 1)) + scale_x_continuous("Question", breaks = seq(1, 21), labels = seq(1, 21)) + ggtitle("Answers to questions (60% intervals)") + theme_bw() + theme(panel.grid.major.x = element_blank(), panel.grid.minor.x = element_blank())
```

```{r}
ggsave("Aggregated_Intervals.pdf", width = 12, height = 5)
ggsave("Aggregated_Intervals.png", width = 12, height = 5)
```

```{r}
answers_to_plot <- read_csv("Mohanad_alt__prelim_answers.csv")
```

```{r}
answers_to_plot <- answers_to_plot %>% 
  gather(key = answer_num, value = answer_result, 1:21) %>% 
  mutate(answer_num = stringr::str_sub(answer_num, 8, -1)) %>% 
  mutate(answer_num = as.integer(answer_num))
  
```

```{r}
ggplot(answers_to_plot) + 
  stat_summary(mapping = aes(answer_num, answer_result), fun.ymin = "min", fun.y = "mean", fun.ymax = "max", size = 0.2) + 
  scale_y_continuous("Estimate", limits = c(0, 1)) + scale_x_continuous("Question", breaks = seq(1, 21), labels = seq(1, 21)) + theme_bw()
```





```{r}
answers_to_plot <- read_csv("Mohanad_prelim_answers_scenario3.csv")
```

```{r}
answers_to_plot <- answers_to_plot %>% 
  gather(key = answer_num, value = answer_result, 1:21) %>% 
  mutate(answer_num = stringr::str_sub(answer_num, 8, -1)) %>% 
  mutate(answer_num = as.integer(answer_num))
  
```

```{r}
ggplot(answers_to_plot) + 
  stat_summary(mapping = aes(answer_num, answer_result), fun.ymin = "min", fun.y = "mean", fun.ymax = "max", size = 0.2) + 
  scale_y_continuous("Estimate", limits = c(0, 1)) + scale_x_continuous("Question", breaks = seq(1, 21), labels = seq(1, 21)) + theme_bw()
```




```{r}
ggplot(answers_to_plot) + 
  stat_summary(mapping = aes(x = answer_num, y = answer_result), fun.ymin = percentile_20, fun.y = "mean", fun.ymax = percentile_80, size = 0.15, colour = "blue") + 
  scale_y_continuous("Estimate", limits = c(0, 1)) + scale_x_continuous("Question", breaks = seq(1, 21), labels = seq(1, 21)) + ggtitle("Answers to questions (60% intervals)") + theme_bw() + theme(panel.grid.major.x = element_blank(), panel.grid.minor.x = element_blank())
ggsave("Scenario3_Aggregated_Intervals.pdf", width = 12, height = 5)
```


```{r}
answers_to_plot <- read_csv("Mohanad_prelim_answers_scenario2.csv")
```

```{r}
answers_to_plot <- answers_to_plot %>% 
  gather(key = answer_num, value = answer_result, 1:21) %>% 
  mutate(answer_num = stringr::str_sub(answer_num, 8, -1)) %>% 
  mutate(answer_num = as.integer(answer_num))
  
```

```{r}
ggplot(answers_to_plot) + 
  stat_summary(mapping = aes(x = answer_num, y = answer_result), fun.ymin = percentile_20, fun.y = "mean", fun.ymax = percentile_80, size = 0.15, colour = "blue") + 
  scale_y_continuous("Estimate", limits = c(0, 1)) + scale_x_continuous("Question", breaks = seq(1, 21), labels = seq(1, 21)) + ggtitle("Answers to questions (60% intervals)") + theme_bw() + theme(panel.grid.major.x = element_blank(), panel.grid.minor.x = element_blank())
ggsave("Scenario2_Aggregated_Intervals.pdf", width = 12, height = 5)
```

```{r}
answers_to_plot <- read_csv("MultiIter5Answers_for_first_40_orgs.csv")
```

```{r}
answers_to_plot <- answers_to_plot %>% 
  gather(key = answer_num, value = answer_result, 1:21) %>% 
  mutate(answer_num = stringr::str_sub(answer_num, 8, -1)) %>% 
  mutate(answer_num = as.integer(answer_num))
  
```

```{r}
ggplot(answers_to_plot) + 
  stat_summary(mapping = aes(x = answer_num, y = answer_result), fun.ymin = percentile_20, fun.y = "mean", fun.ymax = percentile_80, size = 0.15, colour = "blue") + 
  scale_y_continuous("Estimate", limits = c(0, 1)) + scale_x_continuous("Question", breaks = seq(1, 21), labels = seq(1, 21)) + ggtitle("Answers to questions (60% intervals)") + theme_bw() + theme(panel.grid.major.x = element_blank(), panel.grid.minor.x = element_blank())
ggsave("MultiIter5Answers_for_first_40_orgs.pdf", width = 12, height = 5)
```

```{r}
answers_to_plot <- read_csv("Zhengyang_Answers_for_6_thru_11.csv")
```

```{r}
answers_to_plot <- answers_to_plot %>% 
  gather(key = answer_num, value = answer_result, 1:21) %>% 
  mutate(answer_num = stringr::str_sub(answer_num, 8, -1)) %>% 
  mutate(answer_num = as.integer(answer_num))
  
```

```{r}
ggplot(answers_to_plot) + 
  stat_summary(mapping = aes(x = answer_num, y = answer_result), fun.ymin = percentile_20, fun.y = "mean", fun.ymax = percentile_80, size = 0.15, colour = "blue") + 
  scale_y_continuous("Estimate", limits = c(0, 1)) + scale_x_continuous("Question", breaks = seq(1, 21), labels = seq(1, 21)) + ggtitle("Answers to questions (60% intervals)") + theme_bw() + theme(panel.grid.major.x = element_blank(), panel.grid.minor.x = element_blank())
ggsave("Zhengyang_Answers_for_6_thru_11.pdf", width = 12, height = 5)
```


```{r}
answers_to_plot <- read_csv("MultiIter5Answers_for_first_40_orgs.csv")
```

```{r}
answers_to_plot <- answers_to_plot %>% 
  gather(key = answer_num, value = answer_result, 1:21) %>% 
  mutate(answer_num = stringr::str_sub(answer_num, 8, -1)) %>% 
  mutate(answer_num = as.integer(answer_num))
  
```

```{r}
ggplot(answers_to_plot) + 
  stat_summary(mapping = aes(x = answer_num, y = answer_result), fun.ymin = "min", fun.y = "mean", fun.ymax = "max", size = 0.15, colour = "blue", geom = "errorbar") + 
  scale_y_continuous("Estimate", limits = c(0, 1)) + scale_x_continuous("Question", breaks = seq(1, 21), labels = seq(1, 21)) + ggtitle("Answers to questions (full range)") + theme_bw() + theme(panel.grid.major.x = element_blank(), panel.grid.minor.x = element_blank())
ggsave("MultiIter5Answers_for_first_40_orgs_full.pdf", width = 12, height = 5)
```





```{r}
getwd()
file_names = list.files(pattern = "MultiIter5_Answers_Mohanad_")

df_list = list()
for (file in file_names){
  df_list[[file]] = read_csv(file)
}

one_iter_orgs = lapply(df_list,'[',1,)

four_iter_orgs = lapply(df_list,'[',2:5,)

four_iter_orgs_means = lapply(four_iter_orgs, colMeans)

four_iter_orgs_df = bind_rows(four_iter_orgs_means)

colnames(four_iter_orgs_df) %>% str_extract("([0-9])")
  
  regexp <- "[[:digit:]]+"

# process string
str_extract(data, regexp)

```

```{r}
answers_to_plot <- answers_to_plot %>% 
  gather(key = answer_num, value = answer_result, 1:21) %>% 
  mutate(answer_num = stringr::str_sub(answer_num, 8, -1)) %>% 
  mutate(answer_num = as.integer(answer_num))
  
```